import {
  AchievementCategory,
  AchievementTier,
  IAchievementDefinition,
} from '../interface/achievement.interface';

export const APPROVED_ACHIEVEMENT_DEFINITIONS: IAchievementDefinition[] = [
  // --- ATHLETE (8) ---
  {
    id: 'ATH_TURF_DEBUT',
    category: AchievementCategory.ATHLETE,
    tier: AchievementTier.BRONZE,
    title: 'Turf Debut',
    description: 'Play and complete your first match on a FieldFlicks enabled turf.',
    requirementText: 'Play 1 Match',
    metricKey: 'matches_played',
    targetValue: 1,
    xpReward: 100,
    badgeAssetKey: 'bronze-picklebat.png',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'ATH_REGULAR_STARTER',
    category: AchievementCategory.ATHLETE,
    tier: AchievementTier.SILVER,
    title: 'Regular Starter',
    description: 'Consistency is key. Play 10 recorded matches.',
    requirementText: 'Play 10 Matches',
    metricKey: 'matches_played',
    targetValue: 10,
    xpReward: 300,
    badgeAssetKey: 'silver-picklebat.png',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'ATH_CENTURION',
    category: AchievementCategory.ATHLETE,
    tier: AchievementTier.GOLD,
    title: 'Centurion',
    description: 'Become a court veteran by recording 50 full matches.',
    requirementText: 'Play 50 Matches',
    metricKey: 'matches_played',
    targetValue: 50,
    xpReward: 1000,
    badgeAssetKey: 'gold-picklebat.png',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'ATH_SHARP_SHOOTER',
    category: AchievementCategory.ATHLETE,
    tier: AchievementTier.SILVER,
    title: 'Sharp Shooter',
    description: 'Score 25 verified goals across recorded sessions.',
    requirementText: 'Score 25 Goals',
    metricKey: 'goals_scored',
    targetValue: 25,
    xpReward: 350,
    badgeAssetKey: 'silver-sharp.png',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'ATH_GOAL_MACHINE',
    category: AchievementCategory.ATHLETE,
    tier: AchievementTier.GOLD,
    title: 'Goal Machine',
    description: 'Score 100 goals to cement your offensive mastery.',
    requirementText: 'Score 100 Goals',
    metricKey: 'goals_scored',
    targetValue: 100,
    xpReward: 1000,
    badgeAssetKey: 'gold-sharp.png',
    displayOrder: 5,
    isActive: true,
  },
  {
    id: 'ATH_CONSISTENT_PLAYER',
    category: AchievementCategory.ATHLETE,
    tier: AchievementTier.SILVER,
    title: 'Consistent Player',
    description: 'Maintain an active daily gameplay or winning streak of 10 days.',
    requirementText: '10 Day Streak',
    metricKey: 'streak_days',
    targetValue: 10,
    xpReward: 400,
    badgeAssetKey: 'silver-rank.png',
    displayOrder: 6,
    isActive: true,
  },
  {
    id: 'ATH_MVP',
    category: AchievementCategory.ATHLETE,
    tier: AchievementTier.GOLD,
    title: 'MVP',
    description: 'Awarded MVP in 5 competitive match recordings.',
    requirementText: 'Win MVP in 5 Matches',
    metricKey: 'mvp_matches_count',
    targetValue: 5,
    xpReward: 500,
    badgeAssetKey: 'gold-trophy.png',
    displayOrder: 7,
    isActive: true,
  },
  {
    id: 'ATH_TURF_LEGEND',
    category: AchievementCategory.ATHLETE,
    tier: AchievementTier.PLATINUM,
    title: 'Turf Legend',
    description: 'Claim 25 MVP honors across all match formats.',
    requirementText: 'Win MVP in 25 Matches',
    metricKey: 'mvp_matches_count',
    targetValue: 25,
    xpReward: 2000,
    badgeAssetKey: 'platinum-trophy.png',
    displayOrder: 8,
    isActive: true,
  },

  // --- CREATOR (8) ---
  {
    id: 'CRE_FIRST_REEL',
    category: AchievementCategory.CREATOR,
    tier: AchievementTier.BRONZE,
    title: 'First Reel',
    description: 'Upload your first FlickShort highlight reel.',
    requirementText: 'Upload 1 FlickShort',
    metricKey: 'flickshorts_uploaded_count',
    targetValue: 1,
    xpReward: 100,
    badgeAssetKey: 'bronze-reel-badge.png',
    displayOrder: 9,
    isActive: true,
  },
  {
    id: 'CRE_HIGHLIGHT_REEL',
    category: AchievementCategory.CREATOR,
    tier: AchievementTier.SILVER,
    title: 'Highlight Reel',
    description: 'Publish 10 captivating FlickShorts.',
    requirementText: 'Upload 10 FlickShorts',
    metricKey: 'flickshorts_uploaded_count',
    targetValue: 10,
    xpReward: 350,
    badgeAssetKey: 'silver-reel-badge.png',
    displayOrder: 10,
    isActive: true,
  },
  {
    id: 'CRE_CONTENT_MACHINE',
    category: AchievementCategory.CREATOR,
    tier: AchievementTier.GOLD,
    title: 'Content Machine',
    description: 'Publish 50 FlickShorts to build your athletic portfolio.',
    requirementText: 'Upload 50 FlickShorts',
    metricKey: 'flickshorts_uploaded_count',
    targetValue: 50,
    xpReward: 1000,
    badgeAssetKey: 'gold-reel-badge.png',
    displayOrder: 11,
    isActive: true,
  },
  {
    id: 'CRE_CROWD_PLEASER',
    category: AchievementCategory.CREATOR,
    tier: AchievementTier.SILVER,
    title: 'Crowd Pleaser',
    description: 'Receive 100 likes on a single published FlickShort.',
    requirementText: '100 Likes on a Short',
    metricKey: 'peak_likes_single_short',
    targetValue: 100,
    xpReward: 400,
    badgeAssetKey: 'silver-like-badge.png',
    displayOrder: 12,
    isActive: true,
  },
  {
    id: 'CRE_VIRAL_SENSATION',
    category: AchievementCategory.CREATOR,
    tier: AchievementTier.GOLD,
    title: 'Viral Sensation',
    description: 'Hit 1,000 likes on a single highlight clip.',
    requirementText: '1,000 Likes on a Short',
    metricKey: 'peak_likes_single_short',
    targetValue: 1000,
    xpReward: 1200,
    badgeAssetKey: 'gold-like-badge.png',
    displayOrder: 13,
    isActive: true,
  },
  {
    id: 'CRE_TRENDING_CLIP',
    category: AchievementCategory.CREATOR,
    tier: AchievementTier.SILVER,
    title: 'Trending Clip',
    description: 'Have a single FlickShort shared 25 times.',
    requirementText: '25 Shares on a Short',
    metricKey: 'peak_shares_single_short',
    targetValue: 25,
    xpReward: 450,
    badgeAssetKey: 'silver-share-badge.png',
    displayOrder: 14,
    isActive: true,
  },
  {
    id: 'CRE_SHARE_MAGNET',
    category: AchievementCategory.CREATOR,
    tier: AchievementTier.GOLD,
    title: 'Share Magnet',
    description: 'Reach 250 shares on a single highlight clip.',
    requirementText: '250 Shares on a Short',
    metricKey: 'peak_shares_single_short',
    targetValue: 250,
    xpReward: 1200,
    badgeAssetKey: 'gold-share-badge.png',
    displayOrder: 15,
    isActive: true,
  },
  {
    id: 'CRE_REEL_LEGEND',
    category: AchievementCategory.CREATOR,
    tier: AchievementTier.PLATINUM,
    title: 'Reel Legend',
    description: 'Amass 10,000+ views across your published FlickShorts.',
    requirementText: '10K+ Views on Shorts',
    metricKey: 'peak_views_single_short',
    targetValue: 10000,
    xpReward: 2500,
    badgeAssetKey: 'platinum-reel-badge.png',
    displayOrder: 16,
    isActive: true,
  },

  // --- SOCIAL (8) ---
  {
    id: 'SOC_SQUAD_BUILDER',
    category: AchievementCategory.SOCIAL,
    tier: AchievementTier.BRONZE,
    title: 'Squad Builder',
    description: 'Add and connect with 5 teammates in your circle.',
    requirementText: 'Connect 5 Teammates',
    metricKey: 'teammates_connected_count',
    targetValue: 5,
    xpReward: 100,
    badgeAssetKey: 'bronze-social.png',
    displayOrder: 17,
    isActive: true,
  },
  {
    id: 'SOC_TEAM_CAPTAIN',
    category: AchievementCategory.SOCIAL,
    tier: AchievementTier.SILVER,
    title: 'Team Captain',
    description: 'Grow your network to 20 connected teammates.',
    requirementText: 'Connect 20 Teammates',
    metricKey: 'teammates_connected_count',
    targetValue: 20,
    xpReward: 350,
    badgeAssetKey: 'silver-social.png',
    displayOrder: 18,
    isActive: true,
  },
  {
    id: 'SOC_CLUB_LEGEND',
    category: AchievementCategory.SOCIAL,
    tier: AchievementTier.GOLD,
    title: 'Club Legend',
    description: 'Connect with 50 teammates in the FieldFlicks network.',
    requirementText: 'Connect 50 Teammates',
    metricKey: 'teammates_connected_count',
    targetValue: 50,
    xpReward: 800,
    badgeAssetKey: 'gold-social.png',
    displayOrder: 19,
    isActive: true,
  },
  {
    id: 'SOC_DIE_HARD_SUPPORTER',
    category: AchievementCategory.SOCIAL,
    tier: AchievementTier.SILVER,
    title: 'Die-Hard Supporter',
    description: 'Achieve the #1 rank for matches watched in your Crew Watch.',
    requirementText: 'Rank #1 in Crew Watch',
    metricKey: 'crew_watch_rank',
    targetValue: 1,
    xpReward: 300,
    badgeAssetKey: 'silver-view.png',
    displayOrder: 20,
    isActive: true,
  },
  {
    id: 'SOC_COMMUNITY_HERO',
    category: AchievementCategory.SOCIAL,
    tier: AchievementTier.GOLD,
    title: 'Community Hero',
    description: 'Refer 10 friends who join and play on FieldFlicks.',
    requirementText: 'Refer 10 Friends',
    metricKey: 'referrals_completed_count',
    targetValue: 10,
    xpReward: 750,
    badgeAssetKey: 'gold-community-hand.png',
    displayOrder: 21,
    isActive: true,
  },
  {
    id: 'SOC_SOCIAL_BUTTERFLY',
    category: AchievementCategory.SOCIAL,
    tier: AchievementTier.SILVER,
    title: 'Social Butterfly',
    description: 'Send 100 messages within team chats and circle communications.',
    requirementText: 'Send 100 Messages',
    metricKey: 'messages_sent_count',
    targetValue: 100,
    xpReward: 300,
    badgeAssetKey: 'silver-message.png',
    displayOrder: 22,
    isActive: true,
  },
  {
    id: 'SOC_NETWORK_KING',
    category: AchievementCategory.SOCIAL,
    tier: AchievementTier.GOLD,
    title: 'Network King',
    description: 'Build a massive network by connecting with 200+ players.',
    requirementText: 'Connect 200+ Players',
    metricKey: 'teammates_connected_count',
    targetValue: 200,
    xpReward: 1500,
    badgeAssetKey: 'gold-globe.png',
    displayOrder: 23,
    isActive: true,
  },
  {
    id: 'SOC_COMMUNITY_LEGEND',
    category: AchievementCategory.SOCIAL,
    tier: AchievementTier.PLATINUM,
    title: 'Community Legend',
    description: 'Rank in the top 1% across social influence and activity metrics.',
    requirementText: 'Top 1% in Social Rank',
    metricKey: 'social_rank_percentile',
    targetValue: 1,
    xpReward: 3000,
    badgeAssetKey: 'platinum-social.png',
    displayOrder: 24,
    isActive: true,
  },

  // --- SPECIAL (16) ---
  {
    id: 'SPC_EARLY_BIRD',
    category: AchievementCategory.SPECIAL,
    tier: AchievementTier.SPECIAL,
    title: 'Early Bird',
    description: 'Pioneer who joined among the first 1,000 users.',
    requirementText: 'Join in First 1000 Users',
    metricKey: 'user_signup_sequence',
    targetValue: 1000,
    xpReward: 500,
    badgeAssetKey: 'star-badge.png',
    displayOrder: 25,
    isActive: true,
  },
  {
    id: 'SPC_7_DAY_STREAK',
    category: AchievementCategory.SPECIAL,
    tier: AchievementTier.SPECIAL,
    title: '7 Day Streak',
    description: 'Maintain active play or engagement for 7 consecutive days.',
    requirementText: 'Active for 7 Days',
    metricKey: 'streak_days',
    targetValue: 7,
    xpReward: 250,
    badgeAssetKey: '7day-badge.png',
    displayOrder: 26,
    isActive: true,
  },
  {
    id: 'SPC_30_DAY_STREAK',
    category: AchievementCategory.SPECIAL,
    tier: AchievementTier.SPECIAL,
    title: '30 Day Streak',
    description: 'Incredible dedication! Active for 30 consecutive days.',
    requirementText: 'Active for 30 Days',
    metricKey: 'streak_days',
    targetValue: 30,
    xpReward: 1000,
    badgeAssetKey: '30day-badge.png',
    displayOrder: 27,
    isActive: true,
  },
  {
    id: 'SPC_HOT_STREAK',
    category: AchievementCategory.SPECIAL,
    tier: AchievementTier.SPECIAL,
    title: 'Hot Streak',
    description: 'Win 15 matches consecutively without a defeat.',
    requirementText: 'Win 15 Matches in a Row',
    metricKey: 'match_win_streak',
    targetValue: 15,
    xpReward: 750,
    badgeAssetKey: 'streak-badge.png',
    displayOrder: 28,
    isActive: true,
  },
  {
    id: 'SPC_CAPTURE_MASTER',
    category: AchievementCategory.SPECIAL,
    tier: AchievementTier.SPECIAL,
    title: 'Capture Master',
    description: 'Record 100 match sessions on FieldFlicks courts.',
    requirementText: 'Record 100 Matches',
    metricKey: 'matches_recorded_count',
    targetValue: 100,
    xpReward: 1500,
    badgeAssetKey: 'camera-badge.png',
    displayOrder: 29,
    isActive: true,
  },
  {
    id: 'SPC_HIGHLIGHT_PRO',
    category: AchievementCategory.SPECIAL,
    tier: AchievementTier.SPECIAL,
    title: 'Highlight Pro',
    description: 'Extract and generate 250 match highlights.',
    requirementText: 'Create 250 Highlights',
    metricKey: 'highlights_created_count',
    targetValue: 250,
    xpReward: 1250,
    badgeAssetKey: 'bolt-badge.png',
    displayOrder: 30,
    isActive: true,
  },
  {
    id: 'SPC_FOUNDING_MEMBER',
    category: AchievementCategory.SPECIAL,
    tier: AchievementTier.SPECIAL,
    title: 'Founding Member',
    description: 'Participated as an official Beta Tester during platform launch.',
    requirementText: 'Beta Tester',
    metricKey: 'beta_tester_flag',
    targetValue: 1,
    xpReward: 1000,
    badgeAssetKey: 'medal-badge.png',
    displayOrder: 31,
    isActive: true,
  },
  {
    id: 'SPC_FOREVER_LEGEND',
    category: AchievementCategory.SPECIAL,
    tier: AchievementTier.SPECIAL,
    title: 'Forever Legend',
    description: 'Ultimate milestone honoring exceptional lifetime achievement.',
    requirementText: 'Lifetime Achievement',
    metricKey: 'lifetime_legend_flag',
    targetValue: 1,
    xpReward: 5000,
    badgeAssetKey: 'trophy-badge.png',
    displayOrder: 32,
    isActive: true,
  },
  {
    id: 'SPC_LIGHTNING_START',
    category: AchievementCategory.SPECIAL,
    tier: AchievementTier.SPECIAL,
    title: 'Lightning Start',
    description: 'Complete 3 matches and upload 1 highlight within your first 48 hours.',
    requirementText: 'Fast Start Milestone',
    metricKey: 'fast_start_flag',
    targetValue: 1,
    xpReward: 300,
    badgeAssetKey: 'bolt-badge.png',
    displayOrder: 33,
    isActive: true,
  },
  {
    id: 'SPC_CHAMPION_SPIRIT',
    category: AchievementCategory.SPECIAL,
    tier: AchievementTier.SPECIAL,
    title: 'Champion Spirit',
    description: 'Win a verified tournament championship or podium finish.',
    requirementText: 'Exceptional Competitive Milestone',
    metricKey: 'exceptional_competitive_flag',
    targetValue: 1,
    xpReward: 1200,
    badgeAssetKey: 'trophy-badge.png',
    displayOrder: 34,
    isActive: true,
  },
  {
    id: 'SPC_MATCHMAKER',
    category: AchievementCategory.SPECIAL,
    tier: AchievementTier.SPECIAL,
    title: 'Matchmaker',
    description: 'Host and organize matches connecting 25+ distinct players.',
    requirementText: 'Build Strong Player Connections',
    metricKey: 'teammates_connected_count',
    targetValue: 25,
    xpReward: 500,
    badgeAssetKey: 'social-badge.png',
    displayOrder: 35,
    isActive: true,
  },
  {
    id: 'SPC_CREATOR_SPARK',
    category: AchievementCategory.SPECIAL,
    tier: AchievementTier.SPECIAL,
    title: 'Creator Spark',
    description: 'Earn a featured spotlight on FieldFlicks Discover feed.',
    requirementText: 'Standout Content Milestone',
    metricKey: 'standout_content_flag',
    targetValue: 1,
    xpReward: 600,
    badgeAssetKey: 'reel-badge.png',
    displayOrder: 36,
    isActive: true,
  },
  {
    id: 'SPC_RISING_STAR',
    category: AchievementCategory.SPECIAL,
    tier: AchievementTier.SPECIAL,
    title: 'Rising Star',
    description: 'Earn community upvotes and recognition in the regional leaderboards.',
    requirementText: 'Notable Community Milestone',
    metricKey: 'community_notable_flag',
    targetValue: 1,
    xpReward: 800,
    badgeAssetKey: 'community-badge.png',
    displayOrder: 37,
    isActive: true,
  },
  {
    id: 'SPC_PERFECT_RUN',
    category: AchievementCategory.SPECIAL,
    tier: AchievementTier.SPECIAL,
    title: 'Perfect Run',
    description: 'Sustain uninterrupted high activity across 60 days.',
    requirementText: 'Sustained High Activity',
    metricKey: 'sustained_activity_flag',
    targetValue: 1,
    xpReward: 1000,
    badgeAssetKey: 'play-badge.png',
    displayOrder: 38,
    isActive: true,
  },
  {
    id: 'SPC_FLICKS_ICON',
    category: AchievementCategory.SPECIAL,
    tier: AchievementTier.SPECIAL,
    title: 'Flicks Icon',
    description: 'Recognized as an iconic contributor across turf and community.',
    requirementText: 'Recognized Across the Community',
    metricKey: 'community_icon_flag',
    targetValue: 1,
    xpReward: 2500,
    badgeAssetKey: 'star-badge.png',
    displayOrder: 39,
    isActive: true,
  },
  {
    id: 'SPC_LEGACY',
    category: AchievementCategory.SPECIAL,
    tier: AchievementTier.SPECIAL,
    title: 'Legacy',
    description: 'Multi-season long-term contribution milestone.',
    requirementText: 'Long-Term Contribution',
    metricKey: 'legacy_contribution_flag',
    targetValue: 1,
    xpReward: 5000,
    badgeAssetKey: 'upload-badge.png',
    displayOrder: 40,
    isActive: true,
  },

  // --- LEVEL / TIER (6) ---
  {
    id: 'LVL_ROOKIE',
    category: AchievementCategory.LEVEL_TIER,
    tier: AchievementTier.BASE,
    title: 'Rookie',
    description: 'Beginning of the athlete journey (Levels 1–9).',
    requirementText: 'Levels 1–9',
    metricKey: 'player_level',
    targetValue: 1,
    xpReward: 50,
    badgeAssetKey: 'bronze-badge.png',
    displayOrder: 41,
    isActive: true,
  },
  {
    id: 'LVL_CONTENDER',
    category: AchievementCategory.LEVEL_TIER,
    tier: AchievementTier.GREEN,
    title: 'Contender',
    description: 'Advancing athlete mastering competitive play (Levels 10–24).',
    requirementText: 'Levels 10–24',
    metricKey: 'player_level',
    targetValue: 10,
    xpReward: 250,
    badgeAssetKey: 'silver-badge.png',
    displayOrder: 42,
    isActive: true,
  },
  {
    id: 'LVL_MASTER',
    category: AchievementCategory.LEVEL_TIER,
    tier: AchievementTier.CYAN,
    title: 'Master',
    description: 'High-tier player commanding the courts (Levels 25–49).',
    requirementText: 'Levels 25–49',
    metricKey: 'player_level',
    targetValue: 25,
    xpReward: 500,
    badgeAssetKey: 'gold-badge.png',
    displayOrder: 43,
    isActive: true,
  },
  {
    id: 'LVL_ELITE',
    category: AchievementCategory.LEVEL_TIER,
    tier: AchievementTier.AMETHYST,
    title: 'Elite',
    description: 'Top-tier athlete demonstrating consistent excellence (Levels 50–74).',
    requirementText: 'Levels 50–74',
    metricKey: 'player_level',
    targetValue: 50,
    xpReward: 1000,
    badgeAssetKey: 'platinum-badge.png',
    displayOrder: 44,
    isActive: true,
  },
  {
    id: 'LVL_CHAMPION',
    category: AchievementCategory.LEVEL_TIER,
    tier: AchievementTier.AMBER,
    title: 'Champion',
    description: 'Pinnacle of competitive mastery (Levels 75–99).',
    requirementText: 'Levels 75–99',
    metricKey: 'player_level',
    targetValue: 75,
    xpReward: 2000,
    badgeAssetKey: 'diamond-badge.png',
    displayOrder: 45,
    isActive: true,
  },
  {
    id: 'LVL_LEGEND',
    category: AchievementCategory.LEVEL_TIER,
    tier: AchievementTier.PRESTIGE,
    title: 'Legend',
    description: 'Highest achievable prestige level in FieldFlicks (Level 100+).',
    requirementText: 'Level 100+',
    metricKey: 'player_level',
    targetValue: 100,
    xpReward: 5000,
    badgeAssetKey: 'ace-badge.png',
    displayOrder: 46,
    isActive: true,
  },
];
