export const PROFILE_PIC_PATH = 'user/:userID/profilePic/:date';
export const AWS_BUCKET_NAME = 'kaito-dev-profile';
export const DURATION_TO_BACKTRACK_SECONDS = 30;
export const MUX_API_BASE_URL = 'https://api.mux.com';
export const HOURLY_RATE = 240;

export {
  RECORDING_UNLOCK_GST_RATE,
  RECORDING_UNLOCK_BASE_INR,
  SPORT_HOURLY_RATE_INR,
  HALF_HOUR_SEC,
} from 'src/utils/recording-pricing';

export const CLIP_PROCESSING = {
  MAX_CONCURRENCY: 5,
  INTER_CLIP_DELAY_SECONDS: 2,
  MAX_ERROR_RETRIES: 3,
  MAX_RATE_LIMIT_RETRIES: 10,
  RATE_LIMIT_DELAY_CAP_SECONDS: 120,
  RATE_LIMIT_BASE_DELAY_SECONDS: 10,
  ERROR_BACKOFF_DELAYS: [0, 30, 120, 300],
  NOT_MY_TURN_DELAY_SECONDS: 30,
  ADVISORY_LOCK_DELAY_SECONDS: 15,
  STUCK_PROCESSING_THRESHOLD_MINUTES: 5,
  STUCK_RATE_LIMITED_THRESHOLD_MINUTES: 10,
  WEBHOOK_EVENTS_CLEANUP_DAYS: 7,
  ASSET_ERRORED_DELAY_SECONDS: 60,
  MAX_ASSET_ERRORED_RETRIES: 2,
};

export const HIGHLIGHT_STATUS = {
  PENDING: 'pending',
  QUEUED: 'queued',
  PROCESSING: 'processing',
  CLIP_CREATED: 'clip_created',
  READY: 'ready',
  FAILED: 'failed',
  RATE_LIMITED: 'rate_limited',
  PERMANENTLY_FAILED: 'permanently_failed',
} as const;

export const TERMINAL_STATUSES = [
  HIGHLIGHT_STATUS.CLIP_CREATED,
  HIGHLIGHT_STATUS.READY,
  HIGHLIGHT_STATUS.PERMANENTLY_FAILED,
] as const;

export const NON_BLOCKING_STATUSES = [
  HIGHLIGHT_STATUS.CLIP_CREATED,
  HIGHLIGHT_STATUS.READY,
  HIGHLIGHT_STATUS.PERMANENTLY_FAILED,
  HIGHLIGHT_STATUS.FAILED,
  HIGHLIGHT_STATUS.RATE_LIMITED,
] as const;

export const SQS_POLL_WAIT_TIME_SECONDS = 20;
export const SQS_MAX_MESSAGES = 1;
export const VISIBILITY_HEARTBEAT_INTERVAL_MS = 60_000;
export const VISIBILITY_EXTENSION_SECONDS = 120;
export const SQS_CONSUMER_CONCURRENCY = 5;
